### ISSUE TITLE
Visit Rayyansaidi.com Today!

### ISSUE THREAD

**Issue by Ryyn-Sd** [nathanchu/advertise#1]
Source Code URL / GitHub Repository: https://git.io/JtZOA

Your URL: [rayyansaidi.com](https://rayyansaidi.com/)

Content:
> Visit rayyansaidi.com to get some info on the wonderfull things that [Rayyan](https://github.com/ryyn-sd) is coding, and a bio about him!

Image: ![https://rayyansaidi.com/icons/icon-384x384.png?v=b5f1d661c2630d2bc25dbcd70e759594](https://rayyansaidi.com/icons/icon-384x384.png?v=b5f1d661c2630d2bc25dbcd70e759594)

**Comment by nathanchu** [comment]
@Ryyn-Sd could you add a title please?

**Comment by Ryyn-Sd** [comment]
Where

**Comment by nathanchu** [comment]
![image](https://user-images.githubusercontent.com/63111210/105642438-ac406880-5e57-11eb-9243-dc110660d52d.png)

**Comment by Ryyn-Sd** [comment]
Oh… Done!

**Comment by nathanchu** [comment]
Added
